[package]
name = "memorabilia"
version = "1.8.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = "1.8.0"
starknet = "2.13.1"

[[target.starknet-contract]]
sierra = true
casm = true
name = "memorabilia_world"

[tool.dojo]
initializer = "src/lib.cairo"
initializer_class_hash = "0xbeef"
rpc_url = "http://localhost:5050/"
account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
world_address = "0x0"

[profile.dev.tool.dojo]
initializer_class_hash = "0xbeef"

[profile.release.tool.dojo]
initializer_class_hash = "0xbeef"

[profile.sepolia.tool.dojo]
initializer_class_hash = "0xbeef"
rpc_url = "https://starknet-sepolia.public.blastapi.io"
account_address = ""
private_key = ""
world_address = ""

[tool]
scarb.allow-prebuilt-plugins = ["dojo_cairo_macros"]

[dev-dependencies]
cairo_test = "2.13.1"
dojo_cairo_test = "1.8.0"

